# Generated by Django 3.0.8 on 2020-07-29 11:42

from django.db import migrations
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('objects', user.models.ProfileManager()),
            ],
        ),
    ]
